# Generated by Django 3.2.2 on 2021-05-10 13:57

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0004_auto_20210510_1414'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='follow',
            name='unique subscribers',
        ),
        migrations.AlterUniqueTogether(
            name='follow',
            unique_together={('user', 'following')},
        ),
    ]
