# Generated by Django 3.2.2 on 2021-05-10 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20210510_1701'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='follow',
            name='unique subscribers',
        ),
    ]
